### ISSUE TITLE
Choropleth layer auto-zoom does not focus on the filtered zone

### ISSUE THREAD

**Issue by indiciagerry** [mapbox/mapboxgl-powerbi#133]
When using a filter to select a "zone" in the map, the autozoom go back to show the full extend of the underlaying vector layer.

To test, simply use the US States choropleth and a list of states as filter. Select a state in the list and the maps zoom full out. It should be zooming in or pan to show the selected state in the same fashion it do when we are using lat/long to filter points.

By the way, good work with this visual!

**Comment by indiciagerry** [comment]
I dont want to play in the source code of the visual and start my own branch of the project.
Can you expose some fields (lat1, lng1, lat2, lng2) in the visual to allow users to set a bounding box from power bi?

**Comment by ryanbaumann** [comment]
@indiciagerry I think we should aim to improve the auto-zoom feature for choropleth layers before release - currently discussing options on this ticket https://github.com/mapbox/mapboxgl-powerbi/issues/134#issuecomment-388686518

**Comment by Mike-Honey** [comment]
I support this feature - It should zoom in or pan to show the selected state.

**Comment by jonathankapoor** [comment]
Hi all. I believe I found the issue relating to autozoom (my original ticket was 204). If the color field is left blank autozoom won't work. If the color field has a value it autozoom will work.

**Comment by samgehret** [comment]
@indiciagerry @Mike-Honey @mrjamesperry @otravers available in beta https://github.com/mapbox/mapboxgl-powerbi/blob/v1.3_beta/dist/mapboxGLMap.pbiviz

**Comment by samgehret** [comment]
@jonathankapoor your issue should be fixed as well in beta ^^

**Comment by iCatCat** [comment]
Hello,
I still have this problem even with a beta-version
![zoom](https://user-images.githubusercontent.com/24561276/46950941-b115ef80-d086-11e8-9d4a-9475fef61a6b.PNG)

**Comment by samgehret** [comment]
Closed this is live. @iCatCat are you able to send over a .pbix file? Should be working now.

**Comment by Mike-Honey** [comment]
I just tested this using the current marketplace version 1.3.  With a 2-level map, the auto-zooming works nicely at the 2nd level. However when showing the top level and filtering the shapes (using a Slicer), the auto-zoom does not work - the map zoom doesn't change at all..

**Comment by PedroRiveraTorresMoir** [comment]
Yes, auto zoom isn’t working for me either.

________________________________

**Comment by ryanbaumann** [comment]
@Mike-Honey @PedroRiveraTorresMoir thanks for the report - we'll open up a new issue to capture the new bug cc/ @samgehret
